filter:
    paths:
        - ./*

build:
    environment:
        php:
            version: '5.6'
            ini:
                'memory_limit': '3G'
    dependencies:
        before:
            - composer self-update
    tests:
        override:
          -
            command: 'bin/phpspec run -f progress -c phpspec-scrutinizer.yml'
            coverage:
                file: 'coverage.clover'
                format: 'php-clover'

#checks:
# cannot run PHP Analyzer with current composer version
#    php:
#        code_rating: true
#        duplication: true

tools:
    php_mess_detector:
        filter:
            excluded_paths:
                - bin/*
                - spec/*
                - vendor/*
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - bin/*
                - spec/*
                - vendor/*
    sensiolabs_security_checker: true
    php_cpd:
        filter:
            excluded_paths:
                - bin/*
                - spec/*
                - vendor/*
    php_loc:
        excluded_dirs:
            - app/
            - bin/
            - vendor/
            - web/
    php_pdepend:
        excluded_dirs:
            - app/
            - bin/
            - vendor/
            - web/
